'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabaseClient'
import { DEV_LOG_STATUS } from '@/lib/constants'
import RichTextEditor from './RichTextEditor'

export default function QuickLogModal({ projectId, allProjects = [], onClose, onSaved }) {
  const supabase=createClient(); const [date,setDate]=useState(''); const [title,setTitle]=useState(''); const [status,setStatus]=useState(DEV_LOG_STATUS[0]); const [detail,setDetail]=useState(''); const [detailOpen,setDetailOpen]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  async function save(e){e.preventDefault();setError('');if(!date||!title.trim())return setError('Tanggal dan judul wajib diisi');setSaving(true);try{const {data:existing,error:fetchError}=await supabase.from('development_logs').select('*').eq('project_id',projectId).order('log_date',{ascending:true}).order('created_at',{ascending:true});if(fetchError)throw fetchError;const count=(existing??[]).filter(l=>l.status===status).length+1;const {error:insertError}=await supabase.from('development_logs').insert({project_id:projectId,log_date:date,title:title.trim(),status,status_count:count,detail});if(insertError)throw insertError;const {data:allLogs}=await supabase.from('development_logs').select('id,status').eq('project_id',projectId).order('log_date',{ascending:true}).order('created_at',{ascending:true});const counters={};for(const item of allLogs??[]){counters[item.status]=(counters[item.status]||0)+1;await supabase.from('development_logs').update({status_count:counters[item.status]}).eq('id',item.id)};onSaved?.()}catch(err){setError(err.message||'Gagal menambah log')}finally{setSaving(false)}}
  return <div className="modal-overlay"><div className="modal-panel modal-panel-medium"><div className="modal-header"><h2>Tambah Development Log</h2><button className="modal-close" onClick={onClose} type="button">&times;</button></div><form className="modal-body" onSubmit={save}>{error&&<div className="error-box">{error}</div>}<div className="field-block"><label>Tanggal</label><input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></div><div className="field-block"><label>Judul</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Misal: MoM Prod" required/></div><div className="field-block"><label>Status</label><select value={status} onChange={e=>setStatus(e.target.value)}>{DEV_LOG_STATUS.map(s=><option key={s} value={s}>{s}</option>)}</select></div><div className="field-block"><div className="detail-label-row"><label>Detail</label><button type="button" className="icon-text-btn" onClick={()=>setDetailOpen(v=>!v)}>{detailOpen?'⌃':'⌄'} {detailOpen?'Sembunyikan':'Tampilkan'}</button></div>{detailOpen&&<RichTextEditor value={detail} onChange={setDetail} allProjects={allProjects} placeholder="Tulis detail development log..."/>}</div><div className="modal-footer"><button className="submit-btn" type="submit" disabled={saving}>{saving?'Menyimpan...':'Tambah Log'}</button></div></form></div></div>
}
